kind: Service
apiVersion: v1
metadata:
  name: homeautomation-backend
  labels:
    app: homeautomation
    tier: backend
spec:
  selector:
    app: homeautomation
    tier: backend
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
    - name: "https"
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
