kind: Service
apiVersion: v1
metadata:
  name: homeautomation-frontend
  labels:
    app: homeautomation
    tier: frontend
spec:
  selector:
    app: homeautomation
    tier: frontend
  ports:
    - name: "http"
      protocol: TCP
      port: 443
      targetPort: 3000
  type: LoadBalancer
  externalIPs: [192.168.1.200]
